### ISSUE TITLE
Pre-release cleanup

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hethers.js#62]
**TODO**
- [ ] Update main hethers README
- [ ] Remove docs folder
- [ ] Remove examples folder
- [ ] Verify exports from the different packages
- [ ] Rename the naming from `@ethersproject` to `@hethers` and from `ethers` to `@hashgraph/hethers`
- [ ] Add link to the docs website in every package
- [ ] Remove unnecessary packages (not used ones) from the build
